# Generated by Django 2.2.6 on 2022-07-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0002_auto_20220728_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayname',
            name='day_name',
            field=models.CharField(choices=[('PON', 'Poniedziałek'), ('WTO', 'Wtorek'), ('SRO', 'Środa'), ('CZW', 'Czwartek'), ('PIA', 'Piątek'), ('SOB', 'Sobota'), ('NIE', 'Niedziela')], max_length=3),
        ),
    ]
