# Generated by Django 2.2.6 on 2022-07-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20220730_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='preparation_method',
            field=models.TextField(null=True),
        ),
    ]
